org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError

# Forzar uso de AndroidX → necesario para que Kommunicate compile y funcione en Android
android.useAndroidX=true

# Habilita Jetifier → convierte librerías antiguas a AndroidX
# Esto garantiza compatibilidad de Kommunicate y otros plugins modernos
android.enableJetifier=true

